//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Qly_NhaHang
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discount
    {
        public int id_Discount { get; set; }
        public string name_Discount { get; set; }
        public int percent_Discount { get; set; }
        public string type_Discount { get; set; }
        public string condition_Discount { get; set; }
    }
}
