//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Qly_NhaHang
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingredient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ingredient()
        {
            this.ImportInfoes = new HashSet<ImportInfo>();
            this.Recipes = new HashSet<Recipe>();
        }
    
        public int id_Ingredient { get; set; }
        public string name_Ingredient { get; set; }
        public string unit_Ingredient { get; set; }
        public Nullable<double> count_Ingredient { get; set; }
        public string status_Ingredient { get; set; }
        public byte[] image_Ingredient { get; set; }
        public string condition_Ingredient { get; set; }
        public string unitkid_Ingredient { get; set; }
        public Nullable<double> countkid_Ingredient { get; set; }
        public Nullable<int> id_Catalog { get; set; }
        public Nullable<double> price_Ingredient { get; set; }
    
        public virtual CatalogIngredient CatalogIngredient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImportInfo> ImportInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recipe> Recipes { get; set; }
    }
}
